export const simulations = [
  {
    id: "Biến thiên nội năng",
    title: "Biến thiên nội năng",
    grade: "Lớp 12",
    description: "Khám phá độ biến thiên nội năng",
    image: "/assets/bien-thien-noi-nang.webp",
    href: "./simulations/Vat-li-12/Chuong-1-Vat-li-nhiet/bien-thien-noi-nang/bien-thien-noi-nang.html",
  },
  {
    id: "Nhiệt hóa hơi",
    title: "Nhiệt hóa hơi",
    grade: "Lớp 12",
    description: "Khám phá nhiệt hóa hơi của nước",
    image: "/assets/nhiet-hoa-hoi.webp",
    href: "./simulations/Vat-li-12/Chuong-1-Vat-li-nhiet/nhiet-hoa-hoi/nhiet-hoa-hoi.html ",
  },
  {
    id: "Nhiệt Nóng Chảy",
    title: "Nhiệt nóng chảy",
    grade: "Lớp 12",
    description: "khám phá nhiệt nóng chảy của nước đá",
    image: "/assets/nhiet-nong-chay-nuoc-da.webp",
    href: "./simulations/Vat-li-12/Chuong-1-Vat-li-nhiet/nhiet-nong-chay/nuoc-da.html",
  },
  {
    id: "Chuyển Động Brown",
    title: "Chuyển động Brown",
    grade: "Lớp 12",
    description: "Khám phá chuyển động Brown",
    image: "/assets/chuyen-dong-brown.webp",
    href: "./simulations/Vat-li-12/Chuong-2-khi-li-tuong/chuyen-dong-brown/chuyen-dong-brown.html",
  },
  {
    id: "Trạng thái của khí lí tưởng",
    title: "Trạng thái của khí lí tưởng",
    grade: "Lớp 12",
    description: "Khám phá các trạng thái của chất khí lí tưởng",
    image: "/assets/trang-thai-khi-li-tuong.webp",
    href: "./simulations/Vat-li-12/Chuong-2-khi-li-tuong/trang-thai-khi-li-tuong/trang-thai-khi-li-tuong.html",
  },
  {
    id: "Mô hình động học phân tử",
    title: "Mô hình động học phân tử",
    grade: "Lớp 12",
    description: "thực hành và khám phá các trạng thái khác nhau của vật chất",
    image: "/assets/mo-hinh-dong-hoc-phan-tu.webp",
    href: "/simulations/Vat-li-12/Chuong-1-Vat-li-nhiet/mo-hinh-dong-hoc-phan-tu/molecular-kinetic.html",
  },
  {
    id: "Mô phỏng con lắc đơn",
    title: "Con lắc đơn",
    grade: "Lớp 11",
    description: "Khám phá dao động của con lắc đơn phương thẳng đứng",
    image: "/assets/con-lac-don-dung.webp",
    href: "./simulations/Vat-li-11/dao-dong/con-lac-don.html",
  },
  {
    id: "Mô phỏng con lắc lò xo",
    title: "Con lắc lò xo",
    grade: "Lớp 11",
    description: "khám phá dao động của con lắc lò xo",
    image: "/assets/con-lac-lo-xo.webp",
    href: "./simulations/Vat-li-11/dao-dong/con-lac-lo-xo.html",
  },
  {
    id: "Thí nghiệm đo nhiệt dung riêng của nước",
    title: "nhiệt dung riêng của nước",
    grade: "Lớp 12",
    description: "khám phá thí nghiệm đo nhiệt dung riêng của nước",
    image: "/assets/nhiet-dung-rieng.webp",
    href: "./simulations/Vat-li-12/Chuong-1-Vat-li-nhiet/nhiet-dung-rieng/ndr.html",
  },
  {
    id: "Chuyển động tròn đều và dao động điều hòa",
    title: "Chuyển động tròn đều và dao động điều hòa",
    grade: "Lớp 11",
    description:
      "Mô phỏng mối liên hệ giữa chuyển động tròn đều và dao động điều hòa",
    image: "/assets/chuyen-dong-tron-dao-dong-dieu-hoa.webp",
    href: "./simulations/Vat-li-11/dao-dong/chuyen-dong-tron-va-dao-dong-dieu-hoa.html",
  },
  {
    id: "Chuyển động thẳng đều",
    title: "Mô tả chuyển động thẳng đều",
    grade: "Lớp 10",
    description: "Khám phá mô phỏng chuyển động thẳng đều",
    image: "/assets/chuyen-dong-thang-deu.webp",
    href: "./simulations/Vat-li-10/mo-ta-chuyen-dong/chuyen-dong-thang-deu.html",
  },
  {
    id: "Hệ quy chiếu",
    title: "Hệ quy chiếu",
    grade: "Lớp 10",
    description: "Khám phá mô phỏng hệ quy chiếu",
    image: "/assets/he-quy-chieu.webp",
    href: "./simulations/Vat-li-10/mo-ta-chuyen-dong/he-quy-chieu.html",
  },
];
